@echo off
cd /d "%~dp0"
echo Test Ollama...
if not exist "C:\Users\armel\AppData\Local\Programs\Ollama\ollama.exe" echo OLLAMA INTROUVABLE
echo Test PowerShell...
powershell -NoProfile -ExecutionPolicy Bypass -Command "Write-Host 'PS OK'"
echo Test port 8765...
powershell -NoProfile -ExecutionPolicy Bypass -Command "try{$t=New-Object Net.Sockets.TcpClient;$t.Connect('127.0.0.1',8765);$t.Close();Write-Host 'PORT DEJA OCCUPE'}catch{Write-Host 'port libre'}"
echo Test B64...
set "B64=dGVzdA=="
powershell -NoProfile -ExecutionPolicy Bypass -Command "Write-Host ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($env:B64)))"
pause